from typing import Optional, List
from sqlmodel import Field, SQLModel, Relationship
from enum import Enum
from datetime import datetime

class BookStatus(str, Enum):
    NEW = "new"
    PROCESSING = "processing"
    READY = "ready"

class ChapterStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"

class Book(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    title: str
    author: str
    cover_path: Optional[str] = None
    status: BookStatus = Field(default=BookStatus.NEW)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    characters: List["Character"] = Relationship(back_populates="book")
    chapters: List["Chapter"] = Relationship(back_populates="book")

class Character(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    book_id: int = Field(foreign_key="book.id")
    name: str
    gender: Optional[str] = None
    description: Optional[str] = None  # Generated by LLM
    assigned_voice_id: Optional[str] = None
    
    book: Book = Relationship(back_populates="characters")

class Chapter(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    book_id: int = Field(foreign_key="book.id")
    position: int
    title: str
    content_text: str
    audio_path: Optional[str] = None
    status: ChapterStatus = Field(default=ChapterStatus.PENDING)
    progress: int = Field(default=0)
    
    book: Book = Relationship(back_populates="chapters")
    segments: List["Segment"] = Relationship(back_populates="chapter")

class Segment(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    chapter_id: int = Field(foreign_key="chapter.id")
    text: str
    speaker_id: Optional[int] = Field(default=None, foreign_key="character.id", nullable=True) # Null for Narrator
    audio_file: Optional[str] = None
    start_time: Optional[float] = None
    end_time: Optional[float] = None
    
    chapter: Chapter = Relationship(back_populates="segments")
